server:
  port: 8080

spring:
  //прописать позже
  spring.mail.host=smtp.gmail.com
  spring.mail.port=587
  spring.mail.username=your.email@gmail.com
  spring.mail.password=yourpassword
  spring.mail.properties.mail.smtp.auth=true
  spring.mail.properties.mail.smtp.starttls.enable=tru
  spring.elasticsearch.rest.uris=http://localhost:9200
  spring.elasticsearch.username=
  spring.elasticsearch.password=

  datasource:
    url: jdbc:mysql://localhost:3306/tootifooti
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

stripe:
  webhook:
    secret=whsec_XXXXXXXXXXXX:
  api:
    key: 124124124

