server:
  port: 8080

spring:
  # почтовые настройки (прописать позже)
  mail:
    host: smtp.gmail.com
    port: 587
    username: your.email@gmail.com
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Elasticsearch (если потребуется)
  elasticsearch:
    rest:
      uris: http://localhost:9200
    username:
    password:

  datasource:
    url: jdbc:mysql://localhost:3306/tootifooti
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

stripe:
  webhook:
    secret: whsec_XXXXXXXXXXXX
  api:
    key: 124124124

antmedia:
  host: antmedia.example.com
  app-name: LiveApp

app:
  hls:
    storage-path: /path/to/hls-storage  # указать реальный путь хранения HLS
    jwtSecret: VerySecretSigningKey1234
    jwtExpirationMillis: 120000    # 2 минуты